/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MaxP2P: typeof import('./src/components/MaxP2P.vue')['default']
    RTCPeerConnection: typeof import('./src/components/RTCPeerConnection.vue')['default']
  }
}
